[package]
name = "oxitone-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
semver = "1"
sha2.workspace = true
crossbeam-queue = "0.3"
oxitone-core = { path = "../core" }
oxitone-transport = { path = "../transport" }
oxitone-graph = { path = "../graph" }
oxitone-instruments = { path = "../instruments" }
oxitone-mixer = { path = "../mixer" }
oxitone-samples = { path = "../samples" }
oxitone-dsp = { path = "../dsp" }
serde.workspace = true
serde_json.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
libloading = "0.8"
oxitone-io-macos = { path = "../io-macos" }

[dev-dependencies]
sha2.workspace = true
