export { anchorPatternExpression, writePatternEdit } from "./editing/pattern-writer.js";
export type { ExpressionAnchor, PatternWriteRequest, PatternWriteResult } from "./editing/pattern-writer.js";
export { SourceOwnership } from "./files/ownership.js";
export type { OwnedSource } from "./files/ownership.js";
export { materializePatternReference, writeLiteralPatternEdit } from "./editing/materialize.js";
export type { MaterializeCandidate, MaterializeSummary } from "./editing/materialize.js";
export { captureSourceReads } from "./files/read-set.js";
export type { SourceRead } from "./files/read-set.js";
export { SourceSaveStore } from "./save/source-save.js";
export type { SourceSaveRequest } from "./save/source-save.js";
export type { SourceSaveFile } from "./save/save-journal.js";
export { ProjectDocument } from "./document/project-document.js";
export type { ProjectDocumentOptions } from "./document/project-document.js";
