[package]
name = "oxitone-napi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
oxitone-graph = { path = "../graph" }
napi = "3"
napi-derive = "3"
serde.workspace = true
serde_json.workspace = true
oxitone-core = { path = "../core" }
oxitone-render = { path = "../render" }
oxitone-samples = { path = "../samples" }
oxitone-io-macos = { path = "../io-macos" }

[build-dependencies]
napi-build = "2"
